name: Update Service A

on:
  push:
    branches:
      - main # Change this to   r main branch name if it's different

jobs:
  update-service-a:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config user.email "aidelojejoshua@gmail.com"
          git config user.name "Aideloje Joshua"
        working-directory: .

      - name: Clone target repository
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/JoshIri360/graphql-service-a target
          rm -rf target/.git # Remove everything but the .git directory
        working-directory: .

      - name: Copy typeDefs and UserModel to Service A
        run: |
          cp typeDefs.js target
          cp UserModel.js target
        working-directory: ./ # Change to the directory where typeDefs.js and UserModel.js are located

      - name: Commit and push changes to Service A
        run: |
          cd target
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic publish from GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
