name: Update Service A

on:
  push:
    branches:
      - main # Change this to   r main branch name if it's different

jobs:
  update-service-a:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config user.email "aidelojejoshua@gmail.com"
          git config user.name "Aideloje Joshua"
        working-directory: .

      - name: Push a file to another repository
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: "typeDefs.js"
          destination_repo: "JoshIri360/graphql-service-a"
          destination_folder: "."
          user_email: "aidelojejoshua@gmail.com"
          user_name: "Aideloje Joshua"
          commit_message: "A custom message for the commit"
