name: Update Service A

on:
  push:
    branches:
      - main # Change this to your main branch name if it's different

jobs:
  update-service-a:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy typeDefs and UserModel to Service A
        run: |
          cp typeDefs.js ../graphql-service-a/typeDefs.js
          cp UserModel.js ../graphql-service-a/UserModel.js
        working-directory: . 

      - name: Push changes to Service A
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ../graphql-service-a/typeDefs.js ../graphql-service-a/UserModel.js
          git commit -m "Update typeDefs and UserModel"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
